# Trabajo Práctico 1 - Matrices de Insumo Producto

## Enunciado

### Consigna 1 - 

Vamos a interpretar las posibles soluciones que podemos obtener del sistema $$ p = (I - A)^{-1} d = Ld $$ Para ello tendremos en cuenta que significa que una matriz sea inversible o no y como impacta esto en las soluciones de mi sistema de ecuaciones lineales.
<p style="text-align: left;">
a) \( (I - A) \ \text{es inversible} \)
</p>
Si la matriz (I - A) tiene inversa esto significa que existe la matriz de Leontief, luego existe solucion unica para este sistema.
<p></p>
<p style="text-align: left;">
b) \( (I - A) \ \text{es inversible y d = 0} \)
</p>
En este caso existe matriz de Leontief pero mi sistema resulta en $p = (I - A)^{-1}\cdot0 = L\cdot0 = 0$  Podemos decir que no existe demanda externa en este caso y que la produccion total es destinada a satisfacer la demanda interna.
<p></p>
<p style="text-align: left;">
c) \( (I - A) \ \text{no es inversible} \)
</p>
Al no existir inversa esto significa que no se puede calcular la matriz de Leontief. Esto tiene dos posibles conclusiones:  <p></p> 
  . El sistema no tiene solucion. <p></p> 
  . Existen infinitas soluciones debido que hay dependencia lineal entre las ecuaciones de mi sistema. Esto puede ocurrir debido a una relacion entre sectores que determinan que no hay unica solucion.
<p style="text-align: left;">
d) \( (I - A) \ \text{no es inversible y d = 0} \)
</p>    
Debido a que no existe matriz de Leontief y que d = 0, para este caso el sistema admite infinitas soluciones para p.



### Consigna 2 -  

In [45]:

import numpy as np
from scipy.linalg import solve_triangular

def calcularLU(A):
    m=A.shape[0]
    n=A.shape[1]
    Ac = A.copy()
    P = np.eye(n)
    
    if m!=n:
        print('Matriz no cuadrada')
        return

    L = np.eye(n) 
        
    for i in range(0,n):   
        max_row = np.argmax(np.abs(Ac[i:n, i])) + i
        if i != max_row:
           
            # Intercambia las filas en Ac
            temp_row = Ac[i, :].copy()  # Copia de la fila i
            Ac[i, :] = Ac[max_row, :]   # Copia la fila max_row en la posición de la fila i
            Ac[max_row, :] = temp_row  # Restaura la fila original de la fila i en la posición de la fila max_row
            
            # Intercambia las filas en P
            temp_row2 = P[i,:].copy()
            P[i,:] = P[max_row,:]
            P[max_row,:] = temp_row2

            
        for j in range(0,n): 
            if i <j: 
                piv = Ac[j][i]/Ac[i][i]
                Ac[j] = Ac[j] - piv * Ac[i]
                L[j][i] = piv
 
    U = Ac
    
    return L, U, P


---

In [36]:

import numpy as np
from scipy.linalg import solve_triangular

def inversaLU(L, U, P):
    n = L.shape[0]
    M_identidad = []
    Inv = np.zeros((n, 0)) 

    if P is None:
        P = np.eye(n)  # Si no se proporciona P, se usa la identidad

    # Crear la matriz identidad
    for i in range(n):
        canonico = np.zeros(n)
        canonico[i] = 1
        M_identidad.append(canonico)

    # Resolver el sistema para cada columna de la identidad permutada
    for i in range(n):
        b = P[:, i]  # Columna i de la matriz de permutación
        x = solve_triangular(L, b, lower=True)
        y = solve_triangular(U, x, lower=False)
        Inv = np.column_stack((Inv, y))  # Agregar la columna de la inversa

    return Inv


### Consigna 3 -  

$$
A = \begin{pmatrix}
0.3 & 0.0 & 0.1 \\
0.05 & 1.0 & 0.2 \\
0.1 & 0.15 & 0.1
\end{pmatrix}
, \quad
d = \begin{pmatrix}
100 \\
100 \\
300
\end{pmatrix}
$$


In [44]:
A = np.array([[0.3,0.0,0.1],[0.05,1.0,0.2],[0.1,0.15,0.1]])
d = np.array([100,100,300])

X = (np.eye(3)-A)
print(X)
L, U, P = calcularLU(X)

print( P@(L@U))
print(X == P@(L@U))      # HAY UN ERROR EN LA COLUMNA 1 (ME INTERCAMBIA EL ELEM 2 POR EL 3) ???

resultado = (inversaLU(L,U,P))@d

print(resultado) 
print(np.linalg.inv(np.eye(3)-A)@d)

[[ 0.7   0.   -0.1 ]
 [-0.05  0.   -0.2 ]
 [-0.1  -0.15  0.9 ]]
[[ 0.7         0.         -0.1       ]
 [-0.1         0.         -0.19285714]
 [-0.05       -0.15        0.89285714]]
[[ True  True  True]
 [False  True False]
 [False  True False]]
[   64.03940887 -5305.41871921  -551.72413793]
[   68.96551724 -5149.42528736  -517.24137931]


### Consigna 4 -  